### ISSUE TITLE
Schema selection

### ISSUE THREAD

**Issue by jnewland** [urcomputeringpal/kubevalidator#5]
`.github/kubevalidator.yaml`

```yaml
apiversion: v1alpha
kind: KubeValidatorConfig
spec:
  manifests:
  - glob: config/kubernetes/default/*/*.yaml
    schemas:
    - version: 1.11.0
    - version: 1.8.0
    - baseURL: https://raw.githubusercontent.com/urgithubusername
      type: openshift
      version: 1.11.1
      strict: false
```
