### ISSUE TITLE
Question - Why is my configuration not interpret correctly?

### ISSUE THREAD

**Issue by tomkerkhove** [urcomputeringpal/kubevalidator#54]
Currently configuring Kubevalidator for my project and created a PR to validate it (https://github.com/tomkerkhove/promitor/pull/263).

Unfortunately, the check says that no files need to be validated while they are at the location that is configured.

- Config file: https://github.com/tomkerkhove/promitor/blob/master/.github/kubevalidator.yaml
- File to verify: https://github.com/tomkerkhove/promitor/blob/verify-kube-validation/deploy/kubernetes-spec.yaml

What am I doing wrong?

**Comment by jnewland** [comment]
Hey @tomkerkhove! Thanks for giving kubevalidator a shot. 😄

It looks like the manifest glob you have configured (`deploy/*/*.yaml`) doesn't match the path to the file changed in that PR (`deploy/kubernetes-spec.yaml`). Can you try updating the glob to `deploy/*.yaml`?

**Comment by jnewland** [comment]
Give this a shot:

```yaml
apiversion: v1alpha
kind: KubeValidatorConfig
spec:
  manifests:
  - glob: deploy/*/*.yaml
    schemas:
    - version: 1.10.0
  - glob: deploy/*.yaml
    schemas:
    - version: 1.10.0
```

It may be worthwhile to add the ability to recursively load all YAML files in a directory at some point in the future!
