### ISSUE TITLE
Question - Files are not discovered

### ISSUE THREAD

**Issue by tomkerkhove** [urcomputeringpal/kubevalidator#63]
I'm trying to wire up Kubevalidator for https://github.com/tomkerkhove/keda which has the following configuration in `.github/kubevalidator.yaml`:
```yaml
apiversion: v1alpha
kind: KubeValidatorConfig
spec:
  manifests:
  - glob: chart/*/*.yaml
    schemas:
    - version: 1.12.0
    - version: 1.13.0
    - version: 1.14.0
  - glob: deploy/*/*.yaml
    schemas:
    - version: 1.12.0
    - version: 1.13.0
    - version: 1.14.0
  - glob: examples/*/*.yaml
    schemas:
    - version: 1.12.0
    - version: 1.13.0
    - version: 1.14.0
```

However, it turns out it does not find any files according to the latest check : https://github.com/tomkerkhove/keda/runs/124457184

However, they are [there](https://github.com/tomkerkhove/keda/tree/master/chart/keda/templates) - What am I doing wrong?
